woowa-techcamp-2022/android-repo-09

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_repo/application/WoowahanRepoApplication.kt
- app/src/main/java/co/kr/woowahan_repo/data/api/ServiceCreator.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/OAuthAccessTokenRequest.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/OAuthAccessTokenResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/service/GithubOAuthAccessTokenService.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/base/BaseActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/base/BaseFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_sign_in.xml
> [FEATURE] Github OAuth Authorization 구현

- app/build.gradle
- app/src/main/java/co/kr/woowahan_repo/data/api/interceptor/AuthInterceptor.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
- build.gradle
> [FEATURE] Github Access Token을 헤더에 추가

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
- app/src/main/res/color/color_text_selector_main_tab.xml
- app/src/main/res/drawable/bg_main.xml
- app/src/main/res/drawable/btn_main_tab_selector.xml
- app/src/main/res/drawable/ic_person_circle.xml
- app/src/main/res/drawable/ic_search.xml
- app/src/main/res/drawable/ic_search_pressed.xml
- app/src/main/res/drawable/ic_selector_search.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
> [FEATURE] Main 화면 디자인 작업

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/view/PopupMenuChooseView.kt
- app/src/main/res/drawable/bg_popup_menu_issue_filter.xml
- app/src/main/res/drawable/ic_arrow_up.xml
- app/src/main/res/drawable/ic_check.xml
- app/src/main/res/drawable/ic_check_pressed.xml
- app/src/main/res/drawable/ic_selector_check.xml
- app/src/main/res/drawable/ic_selector_menu_issue_filter.xml
- app/src/main/res/menu/menu_issue_state.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/themes.xml
> [FEATURE] Issues 화면 팝업 메뉴 디자인

- app/src/main/java/co/kr/woowahan_repo/data/repository/GithubIssuesRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/repository/GithubOAuthRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/repository/GithubRepositorySearchRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/repository/NotificationsRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
- app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubIssuesRepository.kt
- app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubOAuthRepository.kt
- app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubRepositorySearchRepository.kt
- app/src/main/java/co/kr/woowahan_repo/domain/repository/NotificationsRepository.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
Repository 객체의 의미에 맞게 Api 성공 실패에 대한 판별도 포함하도록 변경
> [REFACTOR] Repository 객체의 의미에 맞게 Api 성공 실패에 대한 판별도 포함하도록 변경

- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
> [FIX] Issue Date 파싱 오류 해결

- app/src/main/java/co/kr/woowahan_repo/data/model/repositoryimpl/GithubRepositorySearchRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubSearchLimitResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/repository/GithubRepositorySearchRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/service/GithubSearchLimitService.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
- app/src/main/java/co/kr/woowahan_repo/domain/model/GithubRepositorySearchModel.kt
- app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubRepositorySearchRepository.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
> [FEATURE] Search Api 쿼리 제한 확인 및 개선

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/res/drawable/bg_main.xml
- app/src/main/res/drawable/btn_main_tab_selector.xml
> [DESIGN] Main Design 적용

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/util/ColorUtil.kt
- app/src/main/res/layout/view_search_repository_item.xml
> [FEATURE] 검색 아이템 뷰 - Repository 개발 언어에 따른 색상 구현

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/view/CollapsibleToolbar.kt
- app/src/main/res/layout/activity_search_repository.xml
- app/src/main/res/xml/motion_search_header.xml
> [Design] 검색 화면 Motion Layout 적용

- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubProfileResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubUserRepositoriesResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/repository/GithubProfileRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_repo/data/service/GithubUsersRepositoriesService.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
- app/src/main/java/co/kr/woowahan_repo/domain/model/GithubProfileModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
> [FEATURE] Github Profile 화면에 필요한 데이터 요청하도록 Api 수정

- app/src/main/java/co/kr/woowahan_repo/data/api/interceptor/AuthInterceptor.kt
- app/src/main/java/co/kr/woowahan_repo/data/datasource/WoowahanSharedPreferences.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/OAuthAccessTokenResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
- app/src/main/java/co/kr/woowahan_repo/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceModule.kt
- app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
- app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubTokenDataSource.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
- app/src/main/res/layout/activity_profile.xml
> [REFACTOR] 세부적인 코드 스타일 리팩토링

- app/src/main/java/co/kr/woowahan_repo/di/AppModule.kt
- app/src/main/java/co/kr/woowahan_repo/di/DataSourceModule.kt
- app/src/main/java/co/kr/woowahan_repo/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_repo/di/RetrofitModule.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceModule.kt
- App -> Retrofit -> DataSource -> Service -> Repository 순으로 의존성이 주입되는 흐름
- Service와 Repository는 ViewModel 생명주기 내에서 사용되니 ViewModelComponent 생명주기로 설정
- #52 
close #52
> [REFACTOR] Hilt Module 기능, 생명주기를 고려하여 분리

- app/src/main/java/co/kr/woowahan_repo/application/WoowahanRepoApplication.kt
- app/src/main/java/co/kr/woowahan_repo/data/datasource/WoowahanSharedPreferences.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/OAuthAccessTokenResponse.kt
- app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
- app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
- app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
- app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubTokenDataSource.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/PagingListener.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
- app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/activity_search_repository.xml
> REFACTOR] Service-Locator 브랜치 세부적인 코드 리팩토링

- app/src/main/java/co/kr/woowahan_repo/presentation/PagingListener.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
- app/src/main/res/layout/activity_search_repository.xml
> [REFACTOR] Search Repository Activity progress 위치 조정, Paging Listener 패키지 이동

- app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/util/RecyclerViewExtension.kt
- app/src/main/res/layout/view_issue_item.xml
> [FIX] Issue 탭 문제 수정

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
> [FEATURE] 검색 화면사용환경 개선을 위한 2가지 추가 기능

- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
- app/src/main/res/layout/activity_search_repository.xml
> [FIX] 이전 검색 요청 취소 발생시, progress visible 처리가 꼬이는 문제 수정

- app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
- app/src/main/java/co/kr/woowahan_repo/util/RecyclerViewExtension.kt
- app/src/main/res/layout/view_issue_item.xml
> [FIX][Service-Locator] Issue 탭 문제 수정

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
> [FEATURE][Service-Locator] 검색 화면사용환경 개선을 위한 2가지 추가 기능

- app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
> [FIX][Service-Locator] 이전 검색 요청 취소 발생시, progress visible 처리가 꼬이는 문제 수정

- app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
- app/src/main/res/layout/activity_search_repository.xml
> [FIX] Search Activity Progress 가 모션레이아웃에 가려져서 안보이는 문제 수정

- app/src/main/java/co/kr/woowahan_repo/data/datasource/GithubProfileDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_repo/di/DataSourceModule.kt
- 매번 새로운 로그인을 진행하는데, 구현체를 Shared Preferences 로 사용한다면 의도치 않은 문제가 발생할 수 있다. 때문에 그 구현체를 변경
- #82 
close #82
> [FIX] 프로필 DataSource 구현체 변경 
